name: Actualizar Base de Datos

on:
  schedule:
    - cron: '0 8 * * *'  # Ejecutar a las 8:00 AM UTC todos los días
  workflow_dispatch:  # Permitir ejecución manual
  push:
    branches:
      - dev  # Ejecutar cuando se haga push a la rama dev

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          ref: dev  # Especifica la rama dev

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script de actualización
        run: python main.py

      - name: Subir cambios a GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de GitHub para autenticación
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if git diff --quiet; then
            echo "No hay cambios para commitear."
          else
            git add .
            git commit -m "Actualización automática de la base de datos"
            git push origin dev  # Subir cambios a la rama dev
          fi